name: 'arctic_times_dbt'
version: '1.0.0'
config-version: 2

profile: 'arctic_times'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  database: "ARCTIC_TIMES"
  raw_schema: "RAW"
  marts_schema: "MARTS"
